name: Change Tracking Marker
on:
  - release
      types: [published]

jobs:
  newrelic:
    runs-on: ubuntu-latest
    name: New Relic
    steps:
      # This step builds a var with the release tag value to use later
      - name: Set Release Version from Tag
        run: echo "RELEASE_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
      # This step creates a new Change Tracking Marker
      - name: New Relic Application Deployment Marker
        uses: newrelic/deployment-marker-action@v2.2.0
        with:
          apiKey: ${{ NRAK-59A6OKHCGZ3PFY9S5Q91K5YI7KG }}
          region: "US"
          guid: ${{ NDExNzIyMHxBUE18QVBQTElDQVRJT058MTA5MDg2MTc0NQ }}
          version: "${{ env.RELEASE_VERSION }}"
          user: "${{ github.actor }}"
